prod:
  image: vizzuality/gfw-glad-alerts-api:1.0.3${STAGING}
  ports:
    - "3600"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
//  log_driver: "gelf"
  restart: always
//  log_opt:
//    gelf-address: ${GELF_ADDRESS}
